import { Component, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { ApiService } from '../core/api.service';

@Component({ standalone: true, imports: [ReactiveFormsModule], template: `<section class="card login"><h1>Acceso al sistema</h1><p>Ingresa con tu cuenta asignada.</p><form [formGroup]="form" (ngSubmit)="submit()"><label>Correo<input type="email" formControlName="email"></label><label>Contraseña<input type="password" formControlName="password"></label>@if(error()){<p class="error">{{error()}}</p>}<button [disabled]="form.invalid">Entrar</button></form></section>` })
export class LoginComponent { private auth = inject(AuthService); private router = inject(Router); error = signal(''); form = new FormGroup({ email: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.email] }), password: new FormControl('', { nonNullable: true, validators: [Validators.required] }) }); async submit() { try { await this.auth.signIn(this.form.value.email!, this.form.value.password!); const role = this.auth.profile()?.role; await this.router.navigateByUrl(role === 'admin' ? '/admin' : role === 'gestor' ? '/gestor' : '/captura'); } catch { this.error.set('No fue posible iniciar sesión. Verifica tus credenciales.'); } } }

@Component({ standalone: true, imports: [ReactiveFormsModule], template: `<section class="card login"><h1>Crea tu contraseña</h1><p>Define una contraseña para activar tu cuenta.</p><form [formGroup]="form" (ngSubmit)="submit()"><label>Nueva contraseña<input type="password" formControlName="password" autocomplete="new-password"></label><label>Confirmar contraseña<input type="password" formControlName="confirm" autocomplete="new-password"></label>@if(error()){<p class="error">{{error()}}</p>}<button [disabled]="form.invalid">Activar cuenta</button></form></section>` })
export class ConfirmAccountComponent { private auth = inject(AuthService); private api = inject(ApiService); private router = inject(Router); error = signal(''); form = new FormGroup({ password: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.minLength(8)] }), confirm: new FormControl('', { nonNullable: true, validators: [Validators.required] }) }); async submit() { if (this.form.value.password !== this.form.value.confirm) { this.error.set('Las contraseñas no coinciden.'); return; } const { data: session } = await this.auth.supabase.auth.getSession(); if (!session.session) { this.error.set('El enlace ya no es válido. Solicita una nueva invitación.'); return; } const { error } = await this.auth.supabase.auth.updateUser({ password: this.form.value.password! }); if (error) { this.error.set(error.message); return; } this.api.post<{data: {role: string}}>('/auth/complete-onboarding', {}).subscribe({ next: async (response) => { await this.auth.restore(); await this.router.navigateByUrl(response.data.role === 'gestor' ? '/gestor' : response.data.role === 'admin' ? '/admin' : '/captura'); }, error: () => this.error.set('La contraseña se actualizó, pero no se pudo activar la cuenta. Intenta abrir el enlace de nuevo.') }); } }
