export interface ZoneCatalogEntry {
  neighborhood: string;
  district?: string;
  postalCode?: string;
}

export const aguascalientesDistricts = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12'
];

export const aguascalientesZones: ZoneCatalogEntry[] = [
  { neighborhood: 'Centro', postalCode: '20000' },
  { neighborhood: 'Barrio de Guadalupe' },
  { neighborhood: 'Barrio de San Marcos' },
  { neighborhood: 'Barrio de la Estacion' },
  { neighborhood: 'Barrio del Encino' },
  { neighborhood: 'Barrio de la Purisima' },
  { neighborhood: 'Jardines de la Asuncion' },
  { neighborhood: 'Jardines de Aguascalientes' },
  { neighborhood: 'Jardines del Parque' },
  { neighborhood: 'Jardines de la Concepcion' },
  { neighborhood: 'Bosques del Prado' },
  { neighborhood: 'Prados del Sur' },
  { neighborhood: 'Prados de Villasuncion' },
  { neighborhood: 'Villas de Nuestra Senora de la Asuncion' },
  { neighborhood: 'Villas del Pilar' },
  { neighborhood: 'Villas del Oeste' },
  { neighborhood: 'Villa Teresa' },
  { neighborhood: 'Villa Montanas' },
  { neighborhood: 'Morelos' },
  { neighborhood: 'Ojocaliente' },
  { neighborhood: 'Ojocaliente I' },
  { neighborhood: 'Ojocaliente II' },
  { neighborhood: 'Ojocaliente III' },
  { neighborhood: 'Haciendas de Aguascalientes' },
  { neighborhood: 'Hacienda Nueva' },
  { neighborhood: 'Pilar Blanco' },
  { neighborhood: 'Canteras de San Javier' },
  { neighborhood: 'Trojes de Alonso' },
  { neighborhood: 'Trojes del Sol' },
  { neighborhood: 'La Troje' },
  { neighborhood: 'La Salud' },
  { neighborhood: 'La Estrella' },
  { neighborhood: 'La Soledad' },
  { neighborhood: 'La Herradura' },
  { neighborhood: 'La Rioja' },
  { neighborhood: 'Lomas del Ajedrez' },
  { neighborhood: 'Lomas de Oriente' },
  { neighborhood: 'Lomas del Mirador' },
  { neighborhood: 'Lomas del Campestre' },
  { neighborhood: 'Los Pericos' },
  { neighborhood: 'Los Pocitos' },
  { neighborhood: 'Los Arcos' },
  { neighborhood: 'San Cayetano' },
  { neighborhood: 'San Gerardo' },
  { neighborhood: 'San Marcos' },
  { neighborhood: 'Santa Anita' },
  { neighborhood: 'Santa Elena' },
  { neighborhood: 'Santa Monica' },
  { neighborhood: 'Mision del Campanario' },
  { neighborhood: 'Mision de Santa Lucia' },
  { neighborhood: 'Rinconada Santa Monica' },
  { neighborhood: 'Rinconada del Puertecito' },
  { neighborhood: 'Rinconada los Bosques' },
  { neighborhood: 'Valle de los Cactus' },
  { neighborhood: 'Valle de las Trojes' },
  { neighborhood: 'Valle del Campestre' },
  { neighborhood: 'Paseos de Aguascalientes' },
  { neighborhood: 'Paseos del Sol' },
  { neighborhood: 'Paseos de San Antonio' },
  { neighborhood: 'Pocitos' },
  { neighborhood: 'Pulgas Pandas' },
  { neighborhood: 'Rancho Santa Monica' },
  { neighborhood: 'Residencial del Valle' },
  { neighborhood: 'Residencial San Nicolas' },
  { neighborhood: 'Rodriguez' },
  { neighborhood: 'Gremial' },
  { neighborhood: 'Insurgentes' },
  { neighborhood: 'Macias Arellano' },
  { neighborhood: 'Municipio Libre' },
  { neighborhood: 'Progreso' },
  { neighborhood: 'Constitucion' },
  { neighborhood: 'Jesus Maria Centro', postalCode: '20920' },
  { neighborhood: 'Margaritas' },
  { neighborhood: 'Pabellon de Arteaga Centro' },
  { neighborhood: 'Rincon de Romos Centro' },
  { neighborhood: 'Calvillo Centro' },
  { neighborhood: 'Asientos Centro' },
  { neighborhood: 'Tepezala Centro' },
  { neighborhood: 'San Francisco de los Romo Centro' },
  { neighborhood: 'Cosio Centro' },
  { neighborhood: 'El Llano Centro' },
  { neighborhood: 'San Jose de Gracia Centro' }
];
